REDDIT_ID="YOUR-API-ID-HERE"
REDDIT_SECRET="YOUR-API-KEY-HERE"
REDDIT_PASS="YOUR-REDDOT-PASS-HERE"
REDDIT_USER="YOUR-REDDOT-USER-HERE"

BINANCE_KEY="YOUR-BINANCE-KEY-HERE"
BINANCE_SECRET="YOUR-BINANCE-SECRET-KEY-HERE"